#!/usr/bin/env python3

# fill missing dates (and sort)
# licence: MIT (see LICENSE)

from datetime import datetime, timedelta
import sys
import re

if len(sys.argv) < 3:
        print("usage: prog | fmd [start date] [end date]")
        quit(1)

pat = re.compile(r'^\s*(\d+) (\d{2}/\d{2}/\d{4})')
vals = dict([(datetime.strptime(match.group(2), "%m/%d/%Y"),
              int(match.group(1)))
             for line in sys.stdin
             for match in [pat.match(line)]
             if match])

form = "%d/%m/%Y"
time = datetime.strptime(sys.argv[1], form)
while time < datetime.strptime(sys.argv[2], form):
        print("{}\t{}".format(vals.get(time, 0),
                              time.strftime(form)))
        time += timedelta(days=1)
