#!/usr/bin/env python3

# fill missing times (and sort)
# licence: MIT (see LICENSE)

import sys
import re
from datetime import datetime, timedelta

FORM = "%I:%M %p"
MINUTE = timedelta(minutes=1)

PREV = datetime.strptime("12:00 am", FORM)
PATTERN = re.compile(r"^\s*(.*?)\s+(\d{1,2}:\d{2} (?:am|pm))")

ITEMS = []

for line in sys.stdin:
    match = PATTERN.match(line)
    if not match:
        continue
    ds = match.group(2)
    date = datetime.strptime(ds, FORM)
    ITEMS.append((date, match.group(1)))

FORM = "%H:%M"
ITEMS.sort(key=lambda x: x[0])
for now in ITEMS:
    while PREV < now[0]:
        print("{}\t{}".format(0, datetime.strftime(PREV, FORM)))
        PREV += MINUTE
    print("{}\t{}".format(now[1], datetime.strftime(now[0], FORM)))
    PREV += MINUTE
