#!/usr/bin/env python3

# fill missing times (and sort)
# licence: MIT (see LICENSE)

import datetime
import time
import sys
import fileinput
import re

form = "%I:%M %p"
day = datetime.timedelta(seconds=60)
if sys.argv[1] is not '-':
	prev = datetime.datetime.strptime(sys.argv[1], form)
else:
	prev = datetime.datetime.strptime("12:00 am", form)
if sys.argv[2] is not '-':
	end = datetime.datetime.strptime(sys.argv[2], form)
else:
	prev = datetime.datetime.strptime("11:59 pm", form)

pattern = re.compile(r"^\s*(.*)\s+(\d{2}:\d{2} (?:am|pm))")

items = []
for line in sys.stdin:
	match = pattern.match(line)
	if not match:
		continue
	ds = match.group(2)
	date = datetime.datetime.strptime(ds, form).timestamp()
	items.append((date, match.group(1)))

items.sort(key=lambda x: x[0])
for i in items:
	date = datetime.datetime.utcfromtimestamp(i[0])
	while prev < date-day:
		print("{}\t{}".format(0, prev.strftime(form)))
		prev += day
	print("{}\t{}".format(i[1], date.strftime(form)))
	prev += day
