#!/usr/bin/env python3

# fill missing times (and sort)
# licence: MIT (see LICENSE)

import sys
import re
from datetime import datetime, timedelta

form = "%H:%M"
pat = re.compile(r'\s*(\d+) (\d{2}:\d{2})')
vals = dict([(datetime.strptime(match.group(2), form),
              int(match.group(1)))
             for line in sys.stdin
             for match in [(pat.match(line))]
             if match])

time = datetime.strptime("00:00", form)
while time < datetime.strptime("23:59", form):
    print("{}\t{}".format(vals.get(time, 0),
                          datetime.strftime(time, form)))
    time += timedelta(minutes=1)
