#!/usr/bin/awk -f

# waextr - whatsapp extraction tool
# License: MIT (see LICENSE)

BEGIN {
	req = ARGV[1]
	date = (req ~ /d/)
	time = (req ~ /t/)
	user = (req ~ /u/)
	mess = (req ~ /m/)
	delete ARGV[1]

	FS = "\t"
}

date { printf("%s\t", $1) }
time { printf("%s\t", $2) }
user { printf("%s\t", $3) }
mess { printf("%s ", $4) }
{ print "" }
