#!/usr/bin/perl

# wastat - whatsapp extraction tool
# License: MIT (see LICENSE)

use strict;
use warnings;

$|++;

# command - get what to do
my $C = shift @ARGV;

print "$0: Extracts relevant data out of whatsapp messages
Options (only first charachter required):
	help:	this message
	date:	print all dates per message
	time:	print all times per message
	users:	print all usernames per message
	mess:	print all messages (only text)
	pud:	print persons and dates
        eut:    extract persons and times
	all:	print everything (tabbed)
" and exit if $C =~ /^(h|$)/ or not @ARGV;

die "No such command\n" 
	if $C =~ /^[^hdtumpea]/;

# loop through file
while (<>) {
	# only parse messages 
	next unless /^(\d{2}\/\d{2}\/\d{4}), (\d{2}:\d{2}) - ([^:]*): (.*)$/;

	my ($date, $time, $user, $mess) = ($1, $2, $3, $4);

	$C =~ m/^d/i and print "$date\n";
	$C =~ m/^t/i and print "$time\n";
	$C =~ m/^u/i and print "$user\n";
	$C =~ m/^m/i and print "$mess\n";
	$C =~ m/^p/i and print "$user\t$date\n";
	$C =~ m/^e/i and print "$user\t$time\n";
	$C =~ m/^a/i and print "$date\t$time\t$user\t$mess\n";
}
